server:
  port: ${APP_PORT:8080}

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: driver-exam-reservation-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/driver_exam_reservation_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 30000
  jpa:
    open-in-view: false
    show-sql: ${SHOW_SQL:false}
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    operations-sorter: method
    tags-sorter: alpha

logging:
  level:
    root: info
